function Figure2c

%Figure Properties
set( gcf , 'PaperUnits' , 'Centimeters' ,...
 'Units' , 'Centimeters' ,...
 'PaperOrientation' , 'Portrait' ,...
 'PaperPositionMode' , 'auto' ,...
 'Position' , [2 1 8.5 4.5] );
PAPER = get( gcf , 'Position' );
set ( gcf , 'PaperSize' , [PAPER(3) PAPER(4)] );

%Axis Properties
set( gca , 'Units' , 'centimeters' ,...
 'Position' , [1.3 1.1 6.9 3] ,...
 'FontSize' , 8 ,...
 'FontName' , 'NewCenturySchoolbook' );

holderX = get( gca , 'xlabel' );
holderY = get( gca , 'ylabel' );

xlabel( get( holderX , 'String' ) ,...
 'FontSize' , 9 ,...
 'FontName' , 'NewCenturySchoolBook');
ylabel( get( holderY , 'String' ) ,...
 'FontSize' , 9 ,...
 'FontName' , 'NewCenturySchoolBook');

print -r600 -dpng -loose filename.png
print -r600 -depsc -loose filename.eps


